export enum Deficiencia {
  AUDITIVA = 'AUDITIVA',

  VISUAL = 'VISUAL',

  INTELECTUAL_MENTAL = 'INTELECTUAL_MENTAL',

  MULTIPLA = 'MULTIPLA',

  FISICA = 'FISICA',

  DOENCA_RARA = 'DOENCA_RARA',

  SEM_DEFICIENCIA = 'SEM_DEFICIENCIA',
}
